version: '3.8'

services:
  backend:
    build:
      context: ./backend/backend_venv
    ports:
      - "5000:5000"
    volumes:
      - ./backend/backend_venv:/app
      - ./backend/backend_venv/mydatabase.db:/app/mydatabase.db
    environment:
      - JWT_SECRET=dev-secret
    restart: unless-stopped

  frontend:
    build:
       context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true