# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # ─── Récupération du dépôt ──────────────────────────────
      - uses: actions/checkout@v4

      # ─── Configuration Node + cache npm (root + front) ─────
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      # ───────────────────────────────
      # FRONTEND
      # ───────────────────────────────
      - name: Install root deps (lock racine)
        run: |
          npm ci \
          || (echo "Retry via npmmirror…" \
              && npm cache clean --force \
              && npm ci --registry=https://registry.npmmirror.com)

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci \
          || (echo "Retry via npmmirror…" \
              && npm cache clean --force \
              && npm ci --registry=https://registry.npmmirror.com)

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint --if-present

      - name: Build frontend
        working-directory: frontend
        run: npm run build --if-present

      # ───────────────────────────────
      # BACKEND
      # ───────────────────────────────
      - name: Install backend deps
        working-directory: backend/backend_venv
        run: |
          npm ci \
          || (echo "Retry via npmmirror…" \
              && npm cache clean --force \
              && npm ci --registry=https://registry.npmmirror.com)

      - name: Backend tests
        working-directory: backend/backend_venv
        run: npm test --if-present
