# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---- FRONTEND ----
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            frontend/package-lock.json
            package-lock.json     # racine
            
      - name: Install frontend deps (retry + alt registry)
        working-directory: frontend
        run: |
         npm ci --registry=https://registry.npmmirror.com \
         || (npm cache clean --force \
         && npm ci --registry=https://registry.npmmirror.com)
          

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint --if-present

      - name: Build frontend
        working-directory: frontend
        run: npm run build --if-present

      # ---- BACKEND ----
      - name: Install backend deps (retry on EINTEGRITY)
        working-directory: backend
        run: |
          npm ci || (npm cache clean --force && npm ci)

      - name: Run backend tests
        working-directory: backend
        run: npm test --if-present
